version: '3.8'

services:
  db:
    image: postgres:16
    container_name: project_calendar_db
    environment:
      POSTGRES_USER: <login>
      POSTGRES_PASSWORD: <password>
      POSTGRES_DB: project_calendar_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

  spring-boot-app:
    image: evgeniydockerman/project-calendar-backend
    container_name: project_calendar_spring
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/project_calendar_db
      SPRING_DATASOURCE_USERNAME: <login>
      SPRING_DATASOURCE_PASSWORD: <password>
    depends_on:
      - db
    ports:
      - "8080:8080"

  vue-app:
    image: evgeniydockerman/project-calendar-frontend
    container_name: project_calendar_vue
    ports:
      - "5173:5173"

volumes:
  postgres_data:
