version: '3.8'

services:
  db:
    image: postgres:16
    container_name: project_calendar_db
    environment:
      POSTGRES_USER: <user>
      POSTGRES_PASSWORD: <password>
      POSTGRES_DB: project_calendar_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

  spring-boot-app:
    image: evgeniydockerman/project-calendar-backend
    container_name: project_calendar_spring
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/project_calendar_db
      SPRING_DATASOURCE_USERNAME: <user>
      SPRING_DATASOURCE_PASSWORD: <password>
      SERVER_PORT: 9090
    depends_on:
      - db

  vue-app:
    image: evgeniydockerman/project-calendar-frontend
    container_name: project_calendar_vue
    ports:
      - "2000:2000"
    depends_on:
      - spring-boot-app

volumes:
  postgres_data:
